export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const GET_PARTICIPANT_BY_ID = 'GET_PARTICIPANT_BY_ID';
export const GET_PARTICIPANTS_IDS_LIST='GET_PARTICIPANTS_IDS_LIST';
export const ADD_PARTICIPANTS_ID_LIST='ADD_PARTICIPANTS_ID_LIST';
export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';